"""create persistence tables

Revision ID: 836d38fef917
Revises: 
Create Date: 2026-09-16 02:01:37.570511

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '836d38fef917'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('domain_profile', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_domain_profile'), 'cases', ['domain_profile'], unique=False)
    op.create_index(op.f('ix_cases_external_id'), 'cases', ['external_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_case_id'), 'ai_decisions', ['case_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_decision_id', sa.Uuid(), nullable=False),
    sa.Column('final_category', sa.String(length=255), nullable=False),
    sa.Column('final_urgency', sa.String(length=20), nullable=False),
    sa.Column('final_department', sa.String(length=255), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('discrepancy_impact', sa.String(length=20), nullable=True),
    sa.Column('has_discrepancy', sa.Boolean(), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_decision_id'], ['ai_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_ai_decision_id'), 'audits', ['ai_decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audits_ai_decision_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_ai_decisions_case_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_cases_external_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_domain_profile'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
